module.exports = {
  // 用户头像
  userAvatar: './attachment/avatar',
  // 用户背景
  userBanner: './attachment/avatar',
  // 专栏头像
  columnAvatar: './attachment/avatar',
  // 专栏背景
  columnBanner: './attachment/avatar',
  // 专业LOGO
  forumLogo: './attachment/avatar',
  // 专业背景
  forumBanner: './attachment/avatar',
  // 水印
  watermark: './attachment/website',
  // 首页logo
  homeBigLogo: './attachment/website',
  // 积分图标
  scoreIcon: './attachment/website',
  // 文章封面
  postCover: './attachment/cover',
  // 首页推荐文章的封面（轮播图、固定图）
  recommendThreadCover: './attachment/cover',
  // 聊天中的视频文件
  messageVideo: './message/video',
  // 聊天中的图片文件
  messageImage: './message/image',
  // 聊天中的音频文件
  messageVoice: './message/voice'
};
