// 响应类型
const ResponseTypes = {
  ERROR_TEMPLATE: "ERROR_TEMPLATE",
  FORBIDDEN_BECAUSE_LOGGED: 'FORBIDDEN_BECAUSE_LOGGED',
  FORBIDDEN_BECAUSE_UN_LOGGED: 'FORBIDDEN_BECAUSE_UN_LOGGED',
  FORBIDDEN_BECAUSE_BANNED: 'FORBIDDEN_BECAUSE_BANNED',
  FORBIDDEN_BECAUSE_UN_BANNED: 'FORBIDDEN_BECAUSE_UN_BANNED',
  FORBIDDEN_WITH_MESSAGE: 'FORBIDDEN_WITH_MESSAGE',
  FORBIDDEN: 'FORBIDDEN',

  IS_SENSITIVE_CONTENT: "IS_SENSITIVE_CONTENT",

};

module.exports = {
  ResponseTypes,
};

