const settingIds = {
  auth: 'auth',
  cache: 'cache',
  column: 'column',
  complaint: 'complaint',
  counters: 'counters',
  documentPost: 'documentPost',
  download: 'download',
  editor: 'editor',
  email: 'email',
  exam: 'exam',
  forum: 'forum',
  fund: 'fund',
  grade: 'grade',
  hidePost: 'hidePost',
  home: 'home',
  kcb: 'kcb',
  library: 'library',
  log: 'log',
  login: 'login',
  message: 'message',
  note: 'note',
  page: 'page',
  post: 'post',
  recharge: 'recharge',
  redEnvelope: 'redEnvelope',
  register: 'register',
  review: 'review',
  safe: 'safe',
  score: 'score',
  server: 'server',
  share: 'share',
  shop: 'shop',
  sms: 'sms',
  sticker: 'sticker',
  subscribe: 'subscribe',
  thread: 'thread',
  tools: 'tools',
  topping: 'topping',
  transfer: 'transfer',
  upload: 'upload',
  username: 'username',
  verification: 'verification',
  visit: 'visit',
  xsf: 'xsf',
};

module.exports = {
  settingIds,
};