const { Operations } = require('../settings/operations.js');
module.exports = [
  {
    _id: 'dev',
    color: '#000000',
    description: '管理人员，拥有至高无上的权利',
    abbr: '运',
    displayName: '运维',
    contentClass: [],
    defaultRole: true,
    modifyPostTimeLimit: -1,
    type: 'system',
    operationsId: [],
  },
  {
    _id: 'default',
    color: '#234233',
    description: '普通用户',
    abbr: '普',
    displayName: '普通用户',
    contentClass: [],
    modifyPostTimeLimit: 0.5,
    defaultRole: true,
    type: 'system',
    operationsId: [],
  },
  {
    _id: 'banned',
    color: '#a23422',
    description: '被封禁的用户',
    abbr: '禁',
    displayName: '被封用户',
    contentClass: [],
    defaultRole: true,
    modifyPostTimeLimit: 0,
    type: 'system',
    operationsId: [],
  },
  {
    _id: 'visitor',
    color: '#a23422',
    description: '未登录用户',
    abbr: '游',
    displayName: '游客',
    contentClass: [],
    modifyPostTimeLimit: 0,
    defaultRole: true,
    type: 'system',
    operationsId: [],
  },
  {
    _id: 'moderator',
    color: '#aaaaaa',
    description: '专家',
    abbr: '专',
    displayName: '专家',
    contentClass: [],
    defaultRole: true,
    modifyPostTimeLimit: 0,
    type: 'system',
    operationsId: [
      Operations.creditXsf,
      Operations.showSurveyCertLimit,
      Operations.nkcManagementSticker,
      Operations.visitForumInfoSettings,
      Operations.modifyForumInfo,
      Operations.visitForumCategorySettings,
      Operations.modifyForumCategory,
      Operations.addForumCategory,
      Operations.visitPostHistory,
      Operations.digestPost,
      Operations.unDigestPost,
      Operations.postWarningPost,
      Operations.toppedThread,
      Operations.unToppedThread,
      Operations.violationRecord,
      Operations.review,
      Operations.moveThreads,
      Operations.movePostsToDraft,
      Operations.unblockPosts,
      Operations.getLibraryLogs,
    ],
  },
  {
    _id: 'scholar',
    displayName: '学者',
    abbr: 's',
    modifyPostTimeLimit: 26280,
    color: '#aaaaaa',
    description: '1学术分以上用户自动颁发本证书',
    operationsId: [Operations.viewQuestionRecord, Operations.visitPostHistory],
    defaultRole: true,
    type: 'system',
  },
];
